// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("tests")>]
[<assembly: AssemblyProductAttribute("Site")>]
[<assembly: AssemblyDescriptionAttribute("turtletest.com")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "tests"
    let [<Literal>] AssemblyProduct = "Site"
    let [<Literal>] AssemblyDescription = "turtletest.com"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
